[tool.poetry]
name = "vidalicet"
version = "0.1.0"
description = ""
authors = ["veikak"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
lark = "^1.1.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
